### ISSUE TITLE
treemacs fails to show anything when using native compiled code

### ISSUE THREAD

**Issue by jtl5770** [Alexander-Miller/treemacs#1048]
I am using the following emacs version:
GNU Emacs 29.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version
 3.24.38, cairo version 1.17.8) of 2023-07-23

and I am updating my packages basically every day so I am on an up-to-date treemacs version from melpa as of today.

Since a couple of days (?) I have the problem that when I start treemacs, it opens the sidebar window, but doesn't display anything else. If I remove the compiled files from the eln-cache and restart emacs, and start treemacs right at the beginning before it has time to automatically asynchronously  compile treemacs again, it works. If I wait too long, and the compilation has finished, it won't work of course.

So my assumption is that something breaks the correct functioning of the native compiled treemacs code.

**Comment by sebastiaanspeck** [comment]
Related to #1047?

**Comment by jtl5770** [comment]
Yes, commenting out doom-modeline actually makes it work again. I am just surprised that this only shows up in compiled form.

**Comment by sebastiaanspeck** [comment]
Maybe it will be fixed looking at my latest comment on #1047. Don’t know if that’s the best solution tho..

**Comment by talw** [comment]
Have the same issue as mentioned here and in #1047.

I also use compiled code.
Accordingly, If I `eval-defun` the function `treemacs--setup-mode-line` the problem disappears.

**Comment by practicalli-john** [comment]
Also experiencing this issue in Spacemacs with the latest `treemacs-20230809.2040` package.  Emacs was built with native-compilation enabled and Doom modeline is being used.

As a temporary measure I've pinned an earlier version of treemacs from July which works correctly.  The recipe builds a package called `treemacs-20230703.202907`

```elisp
((treemacs
      :location (recipe
                 :fetcher github
                 :repo "Alexander-Miller/treemacs"
                 :commit "2c576bebccd56ec8e65f4ec5ed5de864d9684fbf"
                 :files (:defaults
                         "Changelog.org"
                         "icons"
                         "src/elisp/treemacs*.el"
                         "src/scripts/treemacs*.py"
                         (:exclude "src/extra/*"))))
```
For spacemacs this recipe was added to `dotspacemacs-additional-packages` with the `treemacs` layer configuration comment out.

I assume this approach will work with doom using the `:pin` option and the same SHA commit value.

**Comment by jtl5770** [comment]
the proposed fix doesn't work for me (no change - treemacs window still blank)

**Comment by greghab** [comment]
I'm just going to leave a comment here, because there was an earlier comment about pinning an older commit as a workaround, and I was looking into implementing that fix for my configuration, and the stuff below worked for me.

The error is a blank treemacs window with: `Error in post-command-hook (treemacs--post-command): (wrong-type-argument number-or-marker-p nil)`, and I believe it appeared after I switched from emacs28 to  emacs29

-  I'm using emacs29 with straight.el and doom-modeline, and you cannot [pin](https://libreddit.swurl.xyz/r/emacs/comments/z3v5xu/is_there_a_way_to_pin_a_package_to_a_specific/) commits with straight, but there's lock files that let you do that I believe, but I only looked a little into that aspect.
  - Anyway the fix for my setup is: Delete `straight/build/treemacs`, clear `straight/repos/treemacs`, download the [3.1 release](https://github.com/Alexander-Miller/treemacs/releases/tag/3.1), copy and paste those files into `straight/repos/treemacs`. Close and reopen emacs, straight will rebuild treemacs (using that downloaded repo), and things should work as normal.
     - This can be seen with just a basic: `(straight-use-package 'treemacs)`

So I'm still running the same `3.1` release according to `treemacs-version`, but now I have no errors.

Why this works? Don't ask me. I'm just a knob-tweaker over here.
- I'm not really sure what these package managers are doing entirely, but now that it works again, I can continue living in ignorance, and be alright.
  - (Issue reproduces if I let straight.el repopulate the repo directory by itself, and fixes when I manually set it from github. I don't see any issues in straight.el's [issue tracker](https://github.com/radian-software/straight.el/issues?q=is%3Aissue+treemacs+is%3Aclosed), so it might just be a me-thing, but it's curious, assuming I'm not the problem here.)

**Comment by andreyyao** [comment]
@greghab I have the same problem without using `straight`.

**Comment by greghab** [comment]
Just to clarify my previous comment and the behavior noted (there's nothing wrong with `straight.el`, it's working fine):
- `straight.el` by default is pulling in the current master: (Aug 9) 6a6171c6d09522a736f1bb91b7e351aa93d0ac2e, which has the error for me.
- Error starts from Aug 7 onward: e4a56c6463c841ad298f30d4e886b4eababf75e9
- **Commits pre-Aug 7, such as (Jul 19) aa0944a29eee48302fd76b6c3a59c5aece114fa6  or the 3.1 tagged release (Apr 8) 127485317a19254ca20ba1910d10edf7dbaa2d97 are fine.**
- **[This commit](https://github.com/Alexander-Miller/treemacs/compare/master...sebastiaanspeck:treemacs:bugfix/fix-doom-modeline) from #1047 does not fix it, so #1050 probably makes sense for now.**

----
And just some misc notes below:

Also just in general instead of `treemacs-version`, the repo commit is a more accurate indicator of the real version being run, because `treemacs-version` is only manually bumped when the release tag is manually bumped, like for [3.1](https://github.com/Alexander-Miller/treemacs/commit/127485317a19254ca20ba1910d10edf7dbaa2d97)
- (And with `straight.el`, because it's just pulling git repos you can just temporarily `git checkout` whatever commit you want in `straight/repos/treemacs`, `git log` to double check the head is set correct, and rebuild whatever commit you want by just deleting the old build `straight/build/treemacs`)

**Comment by LionyxML** [comment]
I am on emacs 30 with no frameworks (doom, space, etc.) and also have this issue.

I install all my packages directly from `package-list-packages` where I have the MELPA repository enabled.

While the PR of the good fella @sebastiaanspeck is not already merged and distributed, my workaround is ensuring treemacs is loaded BEFORE doom-modeline.

`~/.emacs.d/init.el`
```elisp
;; `commented` this custom setting
;;  '(doom-modeline-mode t)
...
(treemacs) ;; turns on
(treemacs) ;; turns off (as I want it to start retracted)
...
(doom-modeline-mode 1)
``` 
This dirty workaround made treemacs work for me.

**Comment by sebastiaanspeck** [comment]
"Fix" is merged (reverted the breaking change). Please test the latest version

**Comment by jtl5770** [comment]
Works again :-)

**Comment by LionyxML** [comment]
Confirming, this is now working for me:

Treemacs: `Version: 20230814.1949 / Commit: 8a1d66f5d658e9d0c0e752b97849271ee6734198`
Doom-modeline: `Version: 20230814.1704 / Commit: 9ce19994654b427679aad4bceb546afe64decb06`

Thanks!

**Comment by greghab** [comment]
Works for me.

**Comment by Alexander-Miller** [comment]
We just pushed a new version of the modeline change. Let me know if it works for you.

**Comment by greghab** [comment]
Looks good to me. Workspace name appears as expected. Thanks for fixing the feature, and for resolving the original PR.
 
00e96c842f0559a4e13f433d4b513de404676671

![image](https://github.com/Alexander-Miller/treemacs/assets/7407672/5df1f5e2-4284-47ee-ae67-247da0942062)
![image](https://github.com/Alexander-Miller/treemacs/assets/7407672/6a9d6470-4bac-403f-803c-3b581cd34801)

8a1d66f5d658e9d0c0e752b97849271ee6734198

![image](https://github.com/Alexander-Miller/treemacs/assets/7407672/a0de73fa-5f25-494f-9c30-d249e8aecf6c)

**Comment by kurnevsky** [comment]
Hm, it's still broken for me. I use it with `lsp-treemacs-errors-list`. First time I call it I get `Symbol’s value as variable is void: treemacs-workspace-name`, and second time `Error in post-command-hook (treemacs--post-command): (wrong-type-argument number-or-marker-p nil)`

**Comment by kurnevsky** [comment]
Aha, it happens because I don't have doom-modeline as a dependency when treemacs is compiled. But I have it in runtime. I use nix for emacs dependency management, which provides dependencies at compile time only when they are specified by a package. So I need to add this dependency manually like this: https://github.com/kurnevsky/nixfiles/commit/4f85b4568ace779007a0f6fb711ba0be7126ecfe But this means that treemacs will be broken in nix for anyone else who uses it together with doom-modeline...

**Comment by kurnevsky** [comment]
One possible solution would be to avoid compilation of this peace of code by wrapping it to `eval-expression` like `(eval-expression '(this should not be compiled))`.

**Comment by jtl5770** [comment]
Works for me

**Comment by auxsvr** [comment]
I'm not using doom-modeline and I have the same issue as https://github.com/Alexander-Miller/treemacs/issues/1048#issuecomment-1683841844. Two more error messages that might be related:
> Hash table data is not a list of even length.
> [Treemacs] The treemacs-extensions module is obsolete, treemacs-treelib should be used instead.

**Comment by Alexander-Miller** [comment]
I pushed a possible fix, try again now.

>  [Treemacs] The treemacs-extensions module is obsolete, treemacs-treelib should be used instead.

That change was made months ago and as far as I know all dependencies made the necessary updates. You are probably using an old version of a package like lsp(-treemacs).

> Hash table data is not a list of even length.

Is this a treemacs message?

**Comment by kurnevsky** [comment]
> as I know all dependencies made the necessary updates

We are still using it in lsp-metals: https://github.com/emacs-lsp/lsp-metals/blob/811f02e4416d208102350ea48404e0310ffea647/lsp-metals-treeview.el#L63 :)

**Comment by auxsvr** [comment]
> > [Treemacs] The treemacs-extensions module is obsolete, treemacs-treelib should be used instead.
>
> That change was made months ago and as far as I know all dependencies made the necessary updates. You are probably using an old version of a package like lsp(-treemacs).

I was using the latest released version. The latest code from git seems to work.
 
> > Hash table data is not a list of even length.
>
> Is this a treemacs message?

I think so. The full message is:
> let*: Hash table data is not a list of even length

and it appears when I double click the directory in treemacs. Only the root directory appears, the rest is empty.
