### ISSUE TITLE
latest update broke treemacs-icons-dired

### ISSUE THREAD

**Issue by mpanarin** [Alexander-Miller/treemacs#480]
I now get error:
`treemacs-icons-dired--display: Wrong type argument: char-or-string-p, nil [3 times]`
when i try to open ranger or deer.
Updating/reinstalling the module doesn't work (

**Comment by Alexander-Miller** [comment]
Did you update both treemacs and dired-icons? It should work when both are up-to-date.

**Comment by mpanarin** [comment]
Well, spacemacs updates all out-of-date packages. I also reinstalled treemacs-icons-dired just in case.

**Comment by Alexander-Miller** [comment]
Well it does work for me, so I'll need a stack trace.

**Comment by Alexander-Miller** [comment]
Well it does work for me, so I'll need a stack trace.

**Comment by Compro-Prasad** [comment]
Same comment twice ^
https://github.com/Alexander-Miller/treemacs/issues/480#issuecomment-509691879
https://github.com/Alexander-Miller/treemacs/issues/480#issuecomment-509691366

**Comment by Alexander-Miller** [comment]
Pretty sure I sent it only once. Must be the spotty wifi on the train :man_shrugging:

**Comment by mpanarin** [comment]
@Alexander-Miller I would be glad to provide it, I just don't know how to obtain a proper traceback :\
`emacs --debug-init` doesn't provide much, or I am using it wrong

**Comment by Alexander-Miller** [comment]
Try `toggle-debug-on-error`.

**Comment by mpanarin** [comment]
Thanks, here is the backtrace
For the info:
emacs27, using spacemacs on develop branch.
Everything worked before the latest update
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  treemacs-icons-dired--display-icons-for-subdir("/home/m-panarin/" #<marker at 1 in m-panarin>)
  treemacs-icons-dired--display()
  run-hooks(dired-after-readin-hook)
  #f(compiled-function (&optional arg noconfirm) "Reread the Dired buffer.\nMust also be called after `dired-actual-switches' have changed.\nShould not fail even on completely garbaged buffers.\nPreserves old cursor, marks/flags, hidden-p.\n\nDired sets `revert-buffer-function' to this function.  The args\nARG and NOCONFIRM, passed from `revert-buffer', are ignored." #<bytecode 0x159429d750ed>)(nil nil)
  apply(#f(compiled-function (&optional arg noconfirm) "Reread the Dired buffer.\nMust also be called after `dired-actual-switches' have changed.\nShould not fail even on completely garbaged buffers.\nPreserves old cursor, marks/flags, hidden-p.\n\nDired sets `revert-buffer-function' to this function.  The args\nARG and NOCONFIRM, passed from `revert-buffer', are ignored." #<bytecode 0x159429d750ed>) (nil nil))
  dired-revert(nil nil)
  revert-buffer()
  dired-sort-other("-alhF")
  ranger-sort(t)
  ranger-setup()
  ranger-mode()
  ranger-find-file("~/")
  ranger()
  funcall-interactively(ranger)
  call-interactively(ranger nil nil)
  command-execute(ranger)
```

**Comment by Alexander-Miller** [comment]
Assuming `treemacs-icons-dired-mode` is enabled, what is the value of `dired-mode-hook`?

**Comment by mpanarin** [comment]
`(treemacs-icons-dired--enable-highlight-correction treemacs--select-icon-set dired-extra-startup centaur-tabs-local-mode treemacs-icons-dired-mode ranger-set-dired-key)`

**Comment by Alexander-Miller** [comment]
Looks like ranger's loading mechanism was disrupting treemacs' icon setup. Should be fixed now.

**Comment by mpanarin** [comment]
Confirming that is fixed, big thanks!

**Comment by mohammedi-haroune** [comment]
Hi, @Alexander-Miller, I'm still facing this using spacemacs 0.300 on emacs 26.3, ubutnu 20.04, fresh install, it happens only on the first try to access a directory, the second access works as expected here's the stack trace:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  treemacs-icons-dired--display-icons-for-subdir("/home/mohammedi/workspace/notes/" #<marker at 1 in notes>)
  treemacs-icons-dired--display()
  run-hooks(dired-after-readin-hook)
  dired-readin()
  dired-internal-noselect("~/workspace/notes/" nil)
  dired-noselect("~/workspace/notes/")
  run-hook-with-args-until-success(dired-noselect "~/workspace/notes/")
  find-file-noselect("~/workspace/notes/" nil nil nil)
  find-file("~/workspace/notes/")
  find-file-existing("~/workspace/notes/")
  (lambda (&rest ignore) (find-file-existing "~/workspace/notes/"))((push-button :args nil :value "~/workspace/notes/" :action (lambda (&rest ignore) (find-file-existing "~/workspace/notes/")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 1107 to 1125 in *spacemacs*> :from #<marker (moves after insertion) at 1107 in *spacemacs*> :to #<marker at 1125 in *spacemacs*>) nil)
  widget-apply((push-button :args nil :value "~/workspace/notes/" :action (lambda (&rest ignore) (find-file-existing "~/workspace/notes/")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 1107 to 1125 in *spacemacs*> :from #<marker (moves after insertion) at 1107 in *spacemacs*> :to #<marker at 1125 in *spacemacs*>) :action nil)
  widget-apply-action((push-button :args nil :value "~/workspace/notes/" :action (lambda (&rest ignore) (find-file-existing "~/workspace/notes/")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 1107 to 1125 in *spacemacs*> :from #<marker (moves after insertion) at 1107 in *spacemacs*> :to #<marker at 1125 in *spacemacs*>) nil)
  widget-button-press(1107)
  funcall-interactively(widget-button-press 1107)
  call-interactively(widget-button-press nil nil)
  command-execute(widget-button-press)
```

**Comment by Alexander-Miller** [comment]
Debugging this will be a bit complicated. Take the following function and replace the one in `treemacs-icons-dired.el` in your package installation directory an then delete the `treemacs-icons-dired.elc` so the changed code is loaded.

```Elisp
(defun treemacs-icons-dired--display-icons-for-subdir (path pos)
  "Display icons for subdir PATH at given POS."
  (unless (member path treemacs-icons-dired--covered-subdirs)
    (add-to-list 'treemacs-icons-dired--covered-subdirs path)
    (treemacs-log "Add Icons For %s at %s" path pos)
    (treemacs-log "Theme: %s" (treemacs-current-theme))
    (treemacs-with-writable-buffer
     (save-excursion
       (goto-char pos)
       (forward-line 2)
       (treemacs-block
        (while (not (eobp))
          (if (dired-move-to-filename nil)
              (progn
                (treemacs-log "Moved to %s" (dired-get-filename nil t))
                (let* ((file (dired-get-filename nil t))
                       (icon (if (file-directory-p file)
                                 treemacs-icon-dir-closed
                               (treemacs-icon-for-file file))))
                  (treemacs-log "Insert icon '%s' with display %s for %s"
                    icon
                    (when (stringp icon) (get-text-property 0 'display icon))
                    file)
                  (insert icon)))
            (treemacs-return nil))
          (forward-line 1) ))))))
```

I will need the additional log output to determine which part is borked and why.

**Comment by mohammedi-haroune** [comment]
Thanks for the response, How can I get the additional log output?

**Comment by Alexander-Miller** [comment]
Just run it, it'll all end up in the messages buffer.

**Comment by mohammedi-haroune** [comment]
Here's the stack trace, after following the said steps:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  insert(nil)
  (let* ((file (dired-get-filename nil t)) (icon (if (file-directory-p file) treemacs-icon-dir-closed (let ((file-downcased (downcase ...))) (ht-get treemacs-icons file-downcased (ht-get treemacs-icons (if ... ... file-downcased) (with-no-warnings treemacs-icon-fallback))))))) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Insert icon '%s' with display %s for %s" icon (if (stringp icon) (progn (get-text-property 0 (quote display) icon))) file))) (insert icon))
  (progn (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Moved to %s" (dired-get-filename nil t)))) (let* ((file (dired-get-filename nil t)) (icon (if (file-directory-p file) treemacs-icon-dir-closed (let ((file-downcased ...)) (ht-get treemacs-icons file-downcased (ht-get treemacs-icons ... ...)))))) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Insert icon '%s' with display %s for %s" icon (if (stringp icon) (progn (get-text-property 0 ... icon))) file))) (insert icon)))
  (if (dired-move-to-filename nil) (progn (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Moved to %s" (dired-get-filename nil t)))) (let* ((file (dired-get-filename nil t)) (icon (if (file-directory-p file) treemacs-icon-dir-closed (let (...) (ht-get treemacs-icons file-downcased ...))))) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Insert icon '%s' with display %s for %s" icon (if (stringp icon) (progn ...)) file))) (insert icon))) (throw (quote --cl-block-__body__--) nil))
  (while (not (eobp)) (if (dired-move-to-filename nil) (progn (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Moved to %s" (dired-get-filename nil t)))) (let* ((file (dired-get-filename nil t)) (icon (if (file-directory-p file) treemacs-icon-dir-closed (let ... ...)))) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Insert icon '%s' with display %s for %s" icon (if ... ...) file))) (insert icon))) (throw (quote --cl-block-__body__--) nil)) (forward-line 1))
  (catch (quote --cl-block-__body__--) (while (not (eobp)) (if (dired-move-to-filename nil) (progn (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Moved to %s" (dired-get-filename nil t)))) (let* ((file (dired-get-filename nil t)) (icon (if ... treemacs-icon-dir-closed ...))) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" ... ...) (format "Insert icon '%s' with display %s for %s" icon ... file))) (insert icon))) (throw (quote --cl-block-__body__--) nil)) (forward-line 1)))
  (save-excursion (goto-char pos) (forward-line 2) (catch (quote --cl-block-__body__--) (while (not (eobp)) (if (dired-move-to-filename nil) (progn (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" ... ...) (format "Moved to %s" ...))) (let* ((file ...) (icon ...)) (if treemacs--no-messages nil (message "%s %s" ... ...)) (insert icon))) (throw (quote --cl-block-__body__--) nil)) (forward-line 1))))
  (let (buffer-read-only) (save-excursion (goto-char pos) (forward-line 2) (catch (quote --cl-block-__body__--) (while (not (eobp)) (if (dired-move-to-filename nil) (progn (if treemacs--no-messages nil (message "%s %s" ... ...)) (let* (... ...) (if treemacs--no-messages nil ...) (insert icon))) (throw (quote --cl-block-__body__--) nil)) (forward-line 1)))))
  (if (member path treemacs-icons-dired--covered-subdirs) nil (add-to-list (quote treemacs-icons-dired--covered-subdirs) path) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Add Icons For %s at %s" path pos))) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" (quote face) (quote font-lock-keyword-face)) (format "Theme: %s" treemacs--current-theme))) (let (buffer-read-only) (save-excursion (goto-char pos) (forward-line 2) (catch (quote --cl-block-__body__--) (while (not (eobp)) (if (dired-move-to-filename nil) (progn (if treemacs--no-messages nil ...) (let* ... ... ...)) (throw (quote --cl-block-__body__--) nil)) (forward-line 1))))))
  treemacs-icons-dired--display-icons-for-subdir("/home/mohammedi/.emacs.d/" #<marker at 1 in .emacs.d>)
  (let ((pos x8) (path x7)) (treemacs-icons-dired--display-icons-for-subdir path pos))
  (let* ((x7 (car x6)) (x8 (cdr x6))) (let ((pos x8) (path x7)) (treemacs-icons-dired--display-icons-for-subdir path pos)))
  (let ((x6 (car --dolist-tail--))) (let* ((x7 (car x6)) (x8 (cdr x6))) (let ((pos x8) (path x7)) (treemacs-icons-dired--display-icons-for-subdir path pos))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((x6 (car --dolist-tail--))) (let* ((x7 (car x6)) (x8 (cdr x6))) (let ((pos x8) (path x7)) (treemacs-icons-dired--display-icons-for-subdir path pos))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- dired-subdir-alist)) (while --dolist-tail-- (let ((x6 (car --dolist-tail--))) (let* ((x7 (car x6)) (x8 (cdr x6))) (let ((pos x8) (path x7)) (treemacs-icons-dired--display-icons-for-subdir path pos))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (progn (set (make-local-variable (quote treemacs-icons-dired-displayed)) t) (set (make-local-variable (quote treemacs-icons)) (aref treemacs--current-theme 3)) (let ((--dolist-tail-- dired-subdir-alist)) (while --dolist-tail-- (let ((x6 (car --dolist-tail--))) (let* ((x7 (car x6)) (x8 (cdr x6))) (let ((pos x8) (path x7)) (treemacs-icons-dired--display-icons-for-subdir path pos))) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (if (and (display-graphic-p) (not treemacs-icons-dired-displayed) dired-subdir-alist) (progn (set (make-local-variable (quote treemacs-icons-dired-displayed)) t) (set (make-local-variable (quote treemacs-icons)) (aref treemacs--current-theme 3)) (let ((--dolist-tail-- dired-subdir-alist)) (while --dolist-tail-- (let ((x6 (car --dolist-tail--))) (let* ((x7 ...) (x8 ...)) (let (... ...) (treemacs-icons-dired--display-icons-for-subdir path pos))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
  treemacs-icons-dired--display()
  run-hooks(dired-after-readin-hook)
  dired-readin()
  dired-internal-noselect("~/.emacs.d/" nil)
  dired-noselect("~/.emacs.d/")
  run-hook-with-args-until-success(dired-noselect "~/.emacs.d/")
  find-file-noselect("~/.emacs.d/" nil nil nil)
  find-file("~/.emacs.d/")
  find-file-existing("~/.emacs.d/")
  (lambda (&rest ignore) (find-file-existing "~/.emacs.d/"))((push-button :args nil :value "~/.emacs.d/" :action (lambda (&rest ignore) (find-file-existing "~/.emacs.d/")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 1575 to 1586 in *spacemacs*> :from #<marker (moves after insertion) at 1575 in *spacemacs*> :to #<marker at 1586 in *spacemacs*>) nil)
  widget-apply((push-button :args nil :value "~/.emacs.d/" :action (lambda (&rest ignore) (find-file-existing "~/.emacs.d/")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 1575 to 1586 in *spacemacs*> :from #<marker (moves after insertion) at 1575 in *spacemacs*> :to #<marker at 1586 in *spacemacs*>) :action nil)
  widget-apply-action((push-button :args nil :value "~/.emacs.d/" :action (lambda (&rest ignore) (find-file-existing "~/.emacs.d/")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 1575 to 1586 in *spacemacs*> :from #<marker (moves after insertion) at 1575 in *spacemacs*> :to #<marker at 1586 in *spacemacs*>) nil)
  widget-button-press(1575)
  funcall-interactively(widget-button-press 1575)
  call-interactively(widget-button-press nil nil)
  command-execute(widget-button-press)
```

**Comment by Alexander-Miller** [comment]
Ok, now also check the content of the Messages buffer. You should see output that looks like this (at least the first 3 lines):

```
[Treemacs] Add Icons For /home/am/.emacs.d/ at #<marker at 1 in .emacs.d>
[Treemacs] Theme: #s(treemacs-theme Default /home/am/Documents/git/treemacs/icons/default #s(hash-table size 450 test equal rehash-size 1.5 rehash-threshold 0.8125 data (root    ......)) #s(hash-table size 450 test equal rehash-size 1.5 rehash-threshold 0.8125 data (root  ......)))
[Treemacs] Moved to /home/am/.emacs.d/.
[Treemacs] Insert icon '  ' with display (image :type imagemagick :file /home/am/Documents/git/treemacs/icons/default/vsc/dir-closed.png :scale 1 :ascent center :width 22 :height 22 :background #2d2d31) for /home/am/.emacs.d/.
[Treemacs] Moved to /home/am/.emacs.d/..
[Treemacs] Insert icon '  ' with display (image :type imagemagick :file /home/am/Documents/git/treemacs/icons/default/vsc/dir-closed.png :scale 1 :ascent center :width 22 :height 22 :background #2d2d31) for /home/am/.emacs.d/..
```

Also how exactly are you starting things? Stuff like `funcall-interactively(widget-button-press 1575)` means you are pressing a button somewhere.

**Comment by mohammedi-haroune** [comment]
Here's what I'm doing:
1. Open Emacs
2. <kbd>SPC</kbd> <kbd>f</kbd> <kbd>f</kbd>
3. Choose any directory

**Messages Buffer**
```
[Treemacs] Add Icons For /home/mohammedi/ at #<marker at 1 in mohammedi>
[Treemacs] Theme: #s(treemacs-theme Default /home/mohammedi/.emacs.d/elpa/26.3/develop/treemacs-20200501.2303/icons/default #s(hash-table size 450 test equal rehash-size 1.5 rehash-threshold 0.8125 data (root    dir-closed    dir-open    tag-leaf    tag-open    tag-closed    error    warning    info    mail    bookmark    screen    house    list    repeat    fallback    el    elc    ledger    yml    yaml    travis.yml    sh    zsh    fish    pdf    c    h    hs    lhs    cabal    lock    py    pyc    md    adoc    asciidoc    rs    jpg    jpeg    bmp    svg    png    xpm    gif    clj    cljs    cljc    ts    tsx    vue    css    properties    conf    config    cfg    ini    xdefaults    xresources    terminalrc    ledgerrc    html    htm    git    gitignore    gitconfig    gitmodules    gitattributes    dart    jar    kt    scala    sbt    go    service    timer    php    js    jsx    babel    hy    json    jl    ex    exs    eex    leex    ml    mli    merlin    ocaml    envrc    pp    dockerfile    docker-compose.yml    vagrantfile    j2    jinja2    webm    mp4    avi    mkv    flv    mov    wmv    mpg    mpeg    mpv    mp3    ogg    oga    wav    flac    tex    racket    rkt    rktl    rktd    scrbl    scribble    plt    erl    hrl    purs    nix    project    sconstruct    sconstript    makefile    license    zip    7z    tar    gz    rar    tar.gz    elm    xml    xsl    accdb    accdt    actionscript    ai    al    angular-cli.json    angular.json    ansible    antlr    anyscript    apacheconf    applescript    appveyor.yml    ino    pde    asp    asm    arm    ahk    babelrc    babelignore    babelrc.js    babelrc.json    babel.config.js    bat    exe    dll    obj    so    o    bazelrc    bazel    bowerrc    bower.json    gemfile    gemfile.lock    cargo.toml    cargo.lock    csr    crt    cer    der    pfx    p12    p7b    p7r    src    crl    sst    stl    class    cmake    cmake-cache    cobol    coffeescript    cpp    cxx    tpp    cc    hpp    hh    feature    cython    pascal    objectpascal    djt    django-html    django-txt    d    dscript    dml    diet    diff    editorconfig    erb    eslintrc    eslintignore    eslintcache    xls    xlsx    xlsm    ods    fods    woff    woff2    ttf    otf    eot    pfa    pfb    sfd    fortran    fortran-modern    fortranfreeform    fsharp    fsproj    gdscript    graphql    helm    java    jenkins    ipynb    key    pem    less    locale    manifest    pom.xml    maven.config    extensions.xml    settings.xml    meson    nginx.conf    nginx    npmignore    npmrc    package.json    package-lock.json    npm-shrinwrap.json    wasm    wat    yarn.lock    yarnrc    yarnclean    yarn-integrity    yarn-metadata.json    yarnignore    pkg    patch    perl6    pgsql    phpunit    phpunit.xml    pipfile    pipfile.lock    pip-requirements    plsql    orcale    pot    potx    potm    pps    ppsx    ppsm    ppt    pptx    pptm    pa    ppa    ppam    sldm    sldx    prettier.config.js    prettierrc.js    prettierrc.json    prettierrc.yml    prettierrc.yaml    pro    prolog    proto    proto3    rake    rakefile    sqlite    db3    sqlite3    swagger    swift    rb    scss    lua    log    lisp    sql    toml    nim    org    pl    pm    perl    vimrc    tridactylrc    vimperatorrc    ideavimrc    vrapperrc    cask    r    re    rei    boolean-data    class    color-palette    constant    document    enumerator    enumitem    event    field    indexer    intellisense-keyword    interface    localvariable    method    namespace    numeric    operator    property    snippet    string    structure    template    collapsed    expanded    classfile    default-folder-opened    default-folder    default-root-folder-opened    default-root-folder    file-type-jar    flutter    folder-open    folder    folder-type-component-opened    folder-type-component    folder-type-library-opened    folder-type-library    folder-type-maven-opened    folder-type-maven    folder-type-package-opened    folder-type-package    icon-create    icon-flat    icon-hierarchical    icon-link    icon-refresh    icon-unlink    jar    library    packagefolder-open    packagefolder    package    java-project    method    object    enum    field    interface    trait    val    var   )) #s(hash-table size 450 test equal rehash-size 1.5 rehash-threshold 0.8125 data (root  dir-closed +  dir-open -  tag-leaf •  tag-open ▸  tag-closed ▾  error •  warning •  info •  mail  bookmark  screen  house  list  repeat  fallback   el   elc   ledger   yml   yaml   travis.yml   sh   zsh   fish   pdf   c   h   hs   lhs   cabal   lock   py   pyc   md   adoc   asciidoc   rs   jpg   jpeg   bmp   svg   png   xpm   gif   clj   cljs   cljc   ts   tsx   vue   css   properties   conf   config   cfg   ini   xdefaults   xresources   terminalrc   ledgerrc   html   htm   git   gitignore   gitconfig   gitmodules   gitattributes   dart   jar   kt   scala   sbt   go   service   timer   php   js   jsx   babel   hy   json   jl   ex   exs   eex   leex   ml   mli   merlin   ocaml   envrc   pp   dockerfile   docker-compose.yml   vagrantfile   j2   jinja2   webm   mp4   avi   mkv   flv   mov   wmv   mpg   mpeg   mpv   mp3   ogg   oga   wav   flac   tex   racket   rkt   rktl   rktd   scrbl   scribble   plt   erl   hrl   purs   nix   project   sconstruct   sconstript   makefile   license   zip   7z   tar   gz   rar   tar.gz   elm   xml   xsl   accdb   accdt   actionscript   ai   al   angular-cli.json   angular.json   ansible   antlr   anyscript   apacheconf   applescript   appveyor.yml   ino   pde   asp   asm   arm   ahk   babelrc   babelignore   babelrc.js   babelrc.json   babel.config.js   bat   exe   dll   obj   so   o   bazelrc   bazel   bowerrc   bower.json   gemfile   gemfile.lock   cargo.toml   cargo.lock   csr   crt   cer   der   pfx   p12   p7b   p7r   src   crl   sst   stl   class - cmake   cmake-cache   cobol   coffeescript   cpp   cxx   tpp   cc   hpp   hh   feature   cython   pascal   objectpascal   djt   django-html   django-txt   d   dscript   dml   diet   diff   editorconfig   erb   eslintrc   eslintignore   eslintcache   xls   xlsx   xlsm   ods   fods   woff   woff2   ttf   otf   eot   pfa   pfb   sfd   fortran   fortran-modern   fortranfreeform   fsharp   fsproj   gdscript   graphql   helm   java   jenkins   ipynb   key   pem   less   locale   manifest   pom.xml   maven.config   extensions.xml   settings.xml   meson   nginx.conf   nginx   npmignore   npmrc   package.json   package-lock.json   npm-shrinwrap.json   wasm   wat   yarn.lock   yarnrc   yarnclean   yarn-integrity   yarn-metadata.json   yarnignore   pkg   patch   perl6   pgsql   phpunit   phpunit.xml   pipfile   pipfile.lock   pip-requirements   plsql   orcale   pot   potx   potm   pps   ppsx   ppsm   ppt   pptx   pptm   pa   ppa   ppam   sldm   sldx   prettier.config.js   prettierrc.js   prettierrc.json   prettierrc.yml   prettierrc.yaml   pro   prolog   proto   proto3   rake   rakefile   sqlite   db3   sqlite3   swagger   swift   rb   scss   lua   log   lisp   sql   toml   nim   org   pl   pm   perl   vimrc   tridactylrc   vimperatorrc   ideavimrc   vrapperrc   cask   r   re   rei   boolean-data - class - color-palette - constant - document - enumerator - enumitem - event - field - indexer - intellisense-keyword - interface - localvariable - method - namespace - numeric - operator - property - snippet - string - structure - template - collapsed - expanded - classfile - default-folder-opened - default-folder - default-root-folder-opened - default-root-folder - file-type-jar - flutter - folder-open - folder - folder-type-component-opened - folder-type-component - folder-type-library-opened - folder-type-library - folder-type-maven-opened - folder-type-maven - folder-type-package-opened - folder-type-package - icon-create - icon-flat - icon-hierarchical - icon-link - icon-refresh - icon-unlink - jar - library - packagefolder-open - packagefolder - package - java-project - method   object   enum   field   interface   trait   val   var  )))
[Treemacs] Moved to /home/mohammedi/.
[Treemacs] Insert icon 'nil' with display nil for /home/mohammedi/.
let*: Wrong type argument: char-or-string-p, nil
```

**Comment by Alexander-Miller** [comment]
Do you use the ranger layer?

**Comment by mohammedi-haroune** [comment]
Here's the list of my `layers`:
```emacs-lisp
dotspacemacs-configuration-layers
   '(html
     javascript
     yaml
     auto-completion
     ;; better-defaults
     emacs-lisp
     git
     helm
     (lsp :variables
          lsp-ui-doc-enable nil)
     markdown
     ;; multiple-cursors
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     (spell-checking :variables
                     spell-checking-enable-auto-dictionary t
                     enable-flyspell-auto-completion nil)
     syntax-checking
     version-control
     treemacs
     (scala :variables
            scala-auto-insert-asterisk-in-comments t
            scala-enable-eldoc t
            scala-enable-gtags t
            scala-auto-start-backend t
            scala-backend 'scala-metals)
     dap ;; new debugger for python layer
     (python :variables
             python-backend 'lsp
             ;; python-tab-width 4
             ;; python-fill-column 99
             python-formatter 'yapf
             ;; python-format-on-save t
             ;; python-sort-imports-on-save t
             python-test-runner 'pytest
             python-pipenv-activate t)
     kivy
     slack
     ;; semantic
     ;; games
     ;; xkcd
     copy-as-format
     )
```

**Comment by Alexander-Miller** [comment]
Does it help if you add the following to your user config:

```Elisp
(with-eval-after-load 'dired
  (treemacs-icons-dired-mode))
```

**Comment by mohammedi-haroune** [comment]
> Does it help if you add the following to your user config:
> 
> ```emacs-lisp
> (with-eval-after-load 'dired
>   (treemacs-icons-dired-mode))
> ```

Yup, it's working now.

**Comment by Alexander-Miller** [comment]
Turns out a fix is already on the way https://github.com/syl20bnr/spacemacs/pull/13542

**Comment by mohammedi-haroune** [comment]
OK, great, thanks.

**Comment by duianto** [comment]
The Spacemacs PRs changes have been applied to `develop` branch:
[treemacs] load treemacs-icons-dired-mode earlier https://github.com/syl20bnr/spacemacs/pull/13542
