### ISSUE TITLE
hl-line-mode until end of line

### ISSUE THREAD

**Issue by Kaycell** [Alexander-Miller/treemacs#883]
Hello,

Thanks for the amazing work! New to emacs here, I was wondering if it's possible to ensure a line is highlighted until the end?

To avoid this situation:
![Screenshot 2021-12-27 at 21 52 10](https://user-images.githubusercontent.com/8752003/147506462-a3ef020d-d996-4f2a-9066-8e6e04154719.png)

I understand it's the normal behaviour of hl-line-mode in emacs and adding a new line at the end of the buffer is not an option.
I'm wondering if it's possible to add `treemacs-indentation-string` or something like that for the last entry, corresponding to the frame width? Seems hacky but I don't see any other way.
I can work on a PR but I'd rather check before if I'm not missing something obvious about emacs/treemacs configuration

**Comment by Alexander-Miller** [comment]
I've pushed a patch to ensure there's always a newline at the end of the buffer. That means that commands like evil's `G` will now move beyond the final node, but it works the same way in text buffers, so that's acceptable for me.

**Comment by anildigital** [comment]
@Alexander-Miller Issue still exists in `[Treemacs] v2.9.5 (installed 2022.01.18) @ Emacs 28.0.90` 

I just added a new project and folders are so close to each other

![image](https://user-images.githubusercontent.com/266/149872688-9f3500e8-a72f-4041-ad44-955f12e4beab.png)


After I restart Emacs, distance (margin) between folders get corrected

![image](https://user-images.githubusercontent.com/266/149872808-7af22946-74cc-4946-b291-a20ac140cfe7.png)

**Comment by Alexander-Miller** [comment]
More follow-up trouble. I've pushed another patch.
